# Generated by Django 5.2.13 on 2026-05-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("production", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="store",
            field=models.ForeignKey(
                db_column="store_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="sales.store",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "list_price"], name="idx_product_cat_price"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["store", "product"], name="idx_stock_store_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("store", "product"), name="unique_stock_store_product"
            ),
        ),
    ]
