# Generated by Django 5.2.13 on 2026-05-26 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("production", "0002_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                db_column="customer_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                db_column="order_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="production.product",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                db_column="manager_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="sales.staff",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                db_column="staff_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="sales.staff",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="store",
            field=models.ForeignKey(
                blank=True,
                db_column="store_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staffs",
                to="sales.store",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                db_column="store_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="sales.store",
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["store", "active"], name="idx_staff_store_active"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "order_date"], name="idx_order_customer_date"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "status"], name="idx_order_store_status"
            ),
        ),
    ]
