# Generated by Django 5.2.13 on 2026-06-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, default="", max_length=254
            ),
        ),
    ]
