repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.7
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: local
      hooks:
          - id: django-check
            name: django system check
            entry: python manage.py check --settings=config.settings.dev
            language: system
            pass_filenames: false
            always_run: true
